## Desafio Controle de fluxo
na minha concepção não achei necessário fazer um bloco try catch no método main, já que no método contar eu já faço a verifição e não lanço uma exceção verificada na assinatura do método 
